[project]
name = "jwc"
version = "0.2.1"
description = "Default template for PDM package"
authors = [
    {name = "Zjl37", email = "2693911885@qq.com"},
]
dependencies = [
    "ics>=0.7.2",
    "click>=8.1.7",
    "requests>=2.32.3",
    "pandas>=2.2.2",
    "odfpy>=1.4.1",
    "openpyxl>=3.1.5",
    "xlrd>=2.0.1",
    "beautifulsoup4>=4.12.3",
    "html5lib>=1.1",
    "textual-image>=0.7.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "GPLv3"}


[tool.pdm]
distribution = true

[project.scripts]
jwc = "jwc.cli:cli"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
